<?php

use Illuminate\Database\Seeder;
use App\Eloquent\Post;

class PostsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Post::truncate();
        Post::create([
            'ceo_title' => '5 Tips For Real Estate Photography',
            'name' => '5 Tips For Real Estate Photography',
            'image_src' => 'seeds/blog/blog-01.jpg',
            'image_title' => 'seeds/blog/blog-01.jpg',
            'ceo_description' => 'Using quality photos in your real estate listing is essential when selling a property. Better photos generate more interest which potentially equates to more dollars.',
            'description' => '<p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">Taking quality photos is a difficult skill and can be even harder when you put real estate into the mix. Often with real estate photography, you have to work with unfavorable conditions and time constraints, which can mean you photos don’t always turn out quite as expected.</p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">Most professional real estate photographers will provide the home occupants and the agent with a&nbsp;<a href="https://dung13890.github.io/blog-detail.html#" style="color: rgb(241, 197, 90); transition: color 0.2s ease-in-out 0s;">checklist</a>&nbsp;of things they need to do to get the property ready for photography. Often, a listing may not be ready for photos, so you’ll just have to work with it, hope for the best and edit the images later. Most professional photographers edit their photos in the post producing process which is time-consuming and technical, this is where outsourcing the editing process is beneficial for both the photographer and the real estate agent.</p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"=""><img alt="" src="https://dung13890.github.io/images/post1.jpg" style="border-width: initial; border-style: none; max-width: 100%; display: block; width: 100%;"></p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">With the advances in photo editing software items within a photo can now be easily and quickly removed, as if it was never there. Using item removal on your listing photos benefits both Real Estate Agents and Property Managers, here are just some of the benefits:</p>',
        ]);
        Post::create([
            'ceo_title' => 'What are crop sensors, field of view & aperture?',
            'name' => 'What are crop sensors, field of view & aperture?',
            'image_src' => 'seeds/blog/blog-02.jpg',
            'image_title' => 'seeds/blog/blog-02.jpg',
            'ceo_description' => 'So, you’re in the market for a camera, but have no idea what to buy and are faced with a mountain of jargon that makes absolutely no sense',
            'description' => '<p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">Taking quality photos is a difficult skill and can be even harder when you put real estate into the mix. Often with real estate photography, you have to work with unfavorable conditions and time constraints, which can mean you photos don’t always turn out quite as expected.</p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">Most professional real estate photographers will provide the home occupants and the agent with a&nbsp;<a href="https://dung13890.github.io/blog-detail.html#" style="color: rgb(241, 197, 90); transition: color 0.2s ease-in-out 0s;">checklist</a>&nbsp;of things they need to do to get the property ready for photography. Often, a listing may not be ready for photos, so you’ll just have to work with it, hope for the best and edit the images later. Most professional photographers edit their photos in the post producing process which is time-consuming and technical, this is where outsourcing the editing process is beneficial for both the photographer and the real estate agent.</p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"=""><img alt="" src="https://dung13890.github.io/images/post1.jpg" style="border-width: initial; border-style: none; max-width: 100%; display: block; width: 100%;"></p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">With the advances in photo editing software items within a photo can now be easily and quickly removed, as if it was never there. Using item removal on your listing photos benefits both Real Estate Agents and Property Managers, here are just some of the benefits:</p>',
        ]);
        Post::create([
            'ceo_title' => 'Fast & easy hdr photography tips for real estate',
            'name' => 'Fast & easy hdr photography tips for real estate',
            'image_src' => 'seeds/blog/blog-03.jpg',
            'image_title' => 'seeds/blog/blog-03.jpg',
            'ceo_description' => 'At we-edit.com.vn we’re all about making the lives of property professionals and photographers easier.',
            'description' => '<p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">Taking quality photos is a difficult skill and can be even harder when you put real estate into the mix. Often with real estate photography, you have to work with unfavorable conditions and time constraints, which can mean you photos don’t always turn out quite as expected.</p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">Most professional real estate photographers will provide the home occupants and the agent with a&nbsp;<a href="https://dung13890.github.io/blog-detail.html#" style="color: rgb(241, 197, 90); transition: color 0.2s ease-in-out 0s;">checklist</a>&nbsp;of things they need to do to get the property ready for photography. Often, a listing may not be ready for photos, so you’ll just have to work with it, hope for the best and edit the images later. Most professional photographers edit their photos in the post producing process which is time-consuming and technical, this is where outsourcing the editing process is beneficial for both the photographer and the real estate agent.</p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"=""><img alt="" src="https://dung13890.github.io/images/post1.jpg" style="border-width: initial; border-style: none; max-width: 100%; display: block; width: 100%;"></p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">With the advances in photo editing software items within a photo can now be easily and quickly removed, as if it was never there. Using item removal on your listing photos benefits both Real Estate Agents and Property Managers, here are just some of the benefits:</p>',
        ]);
        Post::create([
            'ceo_title' => 'When to use an item removal edit on photos',
            'name' => 'When to use an item removal edit on photos',
            'image_src' => 'seeds/blog/blog-04.jpg',
            'image_title' => 'seeds/blog/blog-04.jpg',
            'ceo_description' => 'Other than the essential, Image Enhancement edit, using Item Removal on images can be one of the most important',
            'description' => '<p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">Taking quality photos is a difficult skill and can be even harder when you put real estate into the mix. Often with real estate photography, you have to work with unfavorable conditions and time constraints, which can mean you photos don’t always turn out quite as expected.</p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">Most professional real estate photographers will provide the home occupants and the agent with a&nbsp;<a href="https://dung13890.github.io/blog-detail.html#" style="color: rgb(241, 197, 90); transition: color 0.2s ease-in-out 0s;">checklist</a>&nbsp;of things they need to do to get the property ready for photography. Often, a listing may not be ready for photos, so you’ll just have to work with it, hope for the best and edit the images later. Most professional photographers edit their photos in the post producing process which is time-consuming and technical, this is where outsourcing the editing process is beneficial for both the photographer and the real estate agent.</p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"=""><img alt="" src="https://dung13890.github.io/images/post1.jpg" style="border-width: initial; border-style: none; max-width: 100%; display: block; width: 100%;"></p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">With the advances in photo editing software items within a photo can now be easily and quickly removed, as if it was never there. Using item removal on your listing photos benefits both Real Estate Agents and Property Managers, here are just some of the benefits:</p>',
        ]);
        Post::create([
            'ceo_title' => '5 Tips For Real Estate Photography',
            'name' => '5 Tips For Real Estate Photography',
            'image_src' => 'seeds/blog/blog-05.jpg',
            'image_title' => 'seeds/blog/blog-05.jpg',
            'ceo_description' => 'Using quality photos in your real estate listing is essential when selling a property.',
            'description' => '<p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">Taking quality photos is a difficult skill and can be even harder when you put real estate into the mix. Often with real estate photography, you have to work with unfavorable conditions and time constraints, which can mean you photos don’t always turn out quite as expected.</p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">Most professional real estate photographers will provide the home occupants and the agent with a&nbsp;<a href="https://dung13890.github.io/blog-detail.html#" style="color: rgb(241, 197, 90); transition: color 0.2s ease-in-out 0s;">checklist</a>&nbsp;of things they need to do to get the property ready for photography. Often, a listing may not be ready for photos, so you’ll just have to work with it, hope for the best and edit the images later. Most professional photographers edit their photos in the post producing process which is time-consuming and technical, this is where outsourcing the editing process is beneficial for both the photographer and the real estate agent.</p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"=""><img alt="" src="https://dung13890.github.io/images/post1.jpg" style="border-width: initial; border-style: none; max-width: 100%; display: block; width: 100%;"></p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">With the advances in photo editing software items within a photo can now be easily and quickly removed, as if it was never there. Using item removal on your listing photos benefits both Real Estate Agents and Property Managers, here are just some of the benefits:</p>',
        ]);
        Post::create([
            'ceo_title' => 'What are crop sensors, field of view & aperture?',
            'name' => 'What are crop sensors, field of view & aperture?',
            'image_src' => 'seeds/blog/blog-06.jpg',
            'image_title' => 'seeds/blog/blog-06.jpg',
            'ceo_description' => 'So, you’re in the market for a camera, but have no idea what to buy and are faced with a mountain of jargon that',
            'description' => '<p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">Taking quality photos is a difficult skill and can be even harder when you put real estate into the mix. Often with real estate photography, you have to work with unfavorable conditions and time constraints, which can mean you photos don’t always turn out quite as expected.</p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">Most professional real estate photographers will provide the home occupants and the agent with a&nbsp;<a href="https://dung13890.github.io/blog-detail.html#" style="color: rgb(241, 197, 90); transition: color 0.2s ease-in-out 0s;">checklist</a>&nbsp;of things they need to do to get the property ready for photography. Often, a listing may not be ready for photos, so you’ll just have to work with it, hope for the best and edit the images later. Most professional photographers edit their photos in the post producing process which is time-consuming and technical, this is where outsourcing the editing process is beneficial for both the photographer and the real estate agent.</p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"=""><img alt="" src="https://dung13890.github.io/images/post1.jpg" style="border-width: initial; border-style: none; max-width: 100%; display: block; width: 100%;"></p><p style="margin-top: 0.9em; margin-bottom: 0px; line-height: 1.6em; font-size: 16px; color: rgb(33, 37, 41); font-family: " open="" sans",="" sans-serif;"="">With the advances in photo editing software items within a photo can now be easily and quickly removed, as if it was never there. Using item removal on your listing photos benefits both Real Estate Agents and Property Managers, here are just some of the benefits:</p>',
        ]);
        if (App::environment('local')) {
            factory(Post::class, 0)->create();
        }
    }
}
